### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by UE2020** [supahero1/alloc#1]
I’m interested in porting your allocator to Rust (via [`GlobalAlloc`](https://doc.rust-lang.org/stable/alloc/alloc/trait.GlobalAlloc.html)) and running some benchmarks, but I can’t do that until the code is licensed.

**Comment by supahero1** [comment]
there is no license so far on purpose, because i am working on the code still. once i am happy with it, there will be multiple benchmarks (against dlmalloc, ptmalloc, tcmalloc, mimalloc) and tests, and there will be a permissible license for you to be able to use it to your liking. you can test the old version of the library (one commit ago) - it worked, but many changes are underway that will change the way you interact with it and partially how it works. nevertheless, the old version can be benchmarked well, and by using `make` it will benchmark it against whatever your default C allocator whatever it is (probably glibc's ptmalloc).
currently i've pushed out what i think is a pretty polished header version (alloc.h) that mostly will not be changed anymore. if you are interested, you can take a look at it.
