### ISSUE TITLE
btw it is safe to ld preload this lib already?

### ISSUE THREAD

**Issue by osevan** [supahero1/alloc#3]
Especially for malloc and free and calloc function replacement? 

Thanks and

Best Regards

**Comment by supahero1** [comment]
I've had my friend run [Zed](https://zed.dev/) (recompiled with this that is) and [a project](https://github.com/UE2020/tenebra) of his for days without any issues, except one time when `exit()` threw a `SIGSEGV`, I'm not sure if it's a me issue or a glib issue though. Since issues haven't appeared anywhere else I would assume this is pretty safe, it has tests too and a stress bench that both pass easily, so you know. And not to mention I'm using it myself too.
